# %%
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dataclasses import dataclass
import os
import scipy.integrate, scipy.interpolate
from pathlib import Path

#%%
# Directories
SCRIPT_DIR = Path(os.path.split(__file__)[0])
HOME = SCRIPT_DIR / ".." / ".."
REF_DIR = HOME / "mcmc_reference" / "ref_3charge"

# %%
# Utilities for reading and working with VDFs
@dataclass
class VDF:
    v: np.ndarray
    g: np.ndarray
    z: float

def read_vdfs(folder):
    vdfs: list[VDF] = []

    for file in os.listdir(folder):
        fullpath = os.path.join(folder, file)
        df = pd.read_csv(fullpath)
        u = df.iloc[:, 0].to_numpy().squeeze() * 1000
        I = df.iloc[:, 1].to_numpy().squeeze()
        integral = scipy.integrate.trapezoid(I, u)
        g = I / integral

        z = float(file.split(".")[0].split("_")[1])
        vdfs.append(VDF(u, g, z))

    vdfs.sort(key = lambda x: x.z)

    return vdfs


# %%
# Read and plot VDFS
vdfs = read_vdfs(SCRIPT_DIR / "data_35uTorr")

fig, ax = plt.subplots(1,1)

for vdf in vdfs:
    ax.plot(vdf.v, vdf.g, label = f"z = {vdf.z} mm")

ax.legend()

fig.savefig(SCRIPT_DIR / "vdfs.png", dpi=200)

# %%
# Run Perez-Luna method
def moment(vdf, order):
    integrand = (vdf.v**order) * vdf.g
    return scipy.integrate.trapezoid(integrand, vdf.v)

def resample(vdf):
    N = len(vdf.v)
    inds = np.unique(np.sort(np.random.choice(np.arange(N), size=N)))
    return VDF(vdf.v[inds], vdf.g[inds], vdf.z)

def calc_perez_luna(vdfs, bootstrap=False):

    if bootstrap:
        vdfs = [resample(vdf) for vdf in vdfs]

    z = np.array([v.z / 1000 for v in vdfs])
    u1 = np.array([moment(vdf, 1) for vdf in vdfs])
    u2 = np.array([moment(vdf, 2) for vdf in vdfs])
    u3 = np.array([moment(vdf, 3) for vdf in vdfs])
    w1 = u1
    w2 = u2/u1
    w3 = u3/u2

    q = 1.6e-19
    M = 131.293 / 6.022e26

    u_mp = np.array([v.v[np.argmax(v.g)] for v in vdfs])
    u_mp_spline = scipy.interpolate.splrep(z, u_mp)


    u_spline = scipy.interpolate.splrep(z, u1)
    w2_spline = scipy.interpolate.splrep(z, w2)
    w3_spline = scipy.interpolate.splrep(z, w3)
    du_dz = scipy.interpolate.splev(z, u_mp_spline, der=1)
    dw2_dz = scipy.interpolate.splev(z, w2_spline, der=1)
    dw3_dz = scipy.interpolate.splev(z, w3_spline, der=1)

    a_z = (w1 * w2) / (2 * w1 - w3) * dw3_dz
    E_z = M / q * a_z
    Ez_simple = M / q * u1 * du_dz
    nu_iz = np.abs(a_z / w2 - (w1 / w2) * dw2_dz)
    
    return z, u_mp, E_z, Ez_simple, nu_iz

z, u_mp, Ez, Ez_simple, nu_iz = calc_perez_luna(vdfs)

bootstrap_results = [calc_perez_luna(vdfs, bootstrap=True) for _ in range(200)]
Ez_bootstrap = np.array([res[2] for res in bootstrap_results]).T
iz_bootstrap = np.array([res[4] for res in bootstrap_results]).T

quantiles = [0.025, 0.5, 0.975]
E_lo, E_mid, E_hi = np.quantile(Ez_bootstrap, quantiles, axis=1)
iz_lo, iz_mid, iz_hi = np.quantile(iz_bootstrap, quantiles, axis=1)

# %%
# Plot perez luna predictions
row_height = 3.5
col_width = 3
fig, axs = plt.subplots(1,3, layout='constrained', figsize=(3 * col_width, row_height))

xargs = dict(xlim=(0, 0.08/0.025), xlabel="z (channel lengths)")
axs[0].set(ylabel = "Ion velocity [km/s]", **xargs)
axs[1].set(ylabel = "Electric field [kV/m]", **xargs)
axs[2].set(ylabel = "Ionization freq. [Hz]", yscale = 'log', **xargs)

z_lch = z / 0.025 + 1
axs[0].plot(z_lch, u_mp)
axs[1].plot(z_lch, E_mid/1000, label = "Perez-luna")
axs[1].fill_between(z_lch, E_lo/1000, E_hi/1000, color = "tab:blue", alpha=0.5)
axs[1].plot(z_lch, Ez_simple / 1000, label = "Simple")

axs[2].plot(z_lch, iz_mid)
axs[2].fill_between(z_lch, iz_lo, iz_hi, color = "tab:blue", alpha=0.5)

fig.savefig(SCRIPT_DIR / "perez_luna.png", dpi=200)

# %%
# Write observation file (1)
z_abs = z + 0.025
df = pd.DataFrame({"z": z_abs, "E": E_mid, "E_lo": E_lo, "E_hi": E_hi, "nu_iz": iz_mid, "nu_iz_lo": iz_lo, "nu_iz_hi": iz_hi})
df.to_csv(SCRIPT_DIR / "perez_luna.csv", index=False)

# Write observation file (2)
df_simple = pd.DataFrame({"z": z_abs, "E": Ez_simple})
df_simple.to_csv(SCRIPT_DIR / "E_simple.csv", index=False)

# %%
# Write TOML output
with open(SCRIPT_DIR / "observation.toml", "w") as fp:
    directory = (REF_DIR / "normalized").absolute()
    print(f"# This file was autogenerated by {os.path.split(__file__)[-1]}", file=fp)
    print(f'base_sim = "{directory}"', file=fp)

    print("\n[params]", file=fp)
    print("anode_mass_flow_rate_kg_s = 5.16e-6", file=fp)
    print("discharge_voltage_v = 300.0", file=fp)
    print("cathode_coupling_voltage = 30.0", file=fp)

    print(f"\n[fields.ui_1]", file=fp)
    print(f"x = {z_abs.tolist()}", file=fp)
    print(f"y = {u_mp.tolist()}", file=fp)
    print("normalized = false", file=fp)

# %%
