# Number of independent sample traces to generate
num_samples = 32
# Batch size of sample generation. If not provided, we do a single batch
batch_size = 256
# Number of sampling steps to take
num_steps = 1024

# Which model to load (ema, best, last) 
model_type = "ema"
# Output directory for generations.
out_dir = "samples/noTe"
# Whether samples in out_dir should be replaced or added to
replace_samples = true
# ODE method
method = "midpoint"

# Stochastic args
S_churn = 0.0       # Set the level of stochasticity (0 for none, >0 for more)
S_tmin = 0.005        # Minimum noise level for stochasticity to apply
S_tmax = 50        # Maximum noise level for stochasticity to apply
S_noise = 1.003     # Noise multiplier for stochasticity
noise_min = 0.002
noise_max = 80.0
step_exponent = 7.0

[observation]
base_sim = "mcmc_reference/ref_3charge/normalized"
stddev = 1.0

[observation.fields]
B = {locs = "all", error_type = "relative"}
nu_an = {locs = "all", error_type = "relative"}